// Generated by CoffeeScript 1.6.3
(function() {
  describe("JavaScript addition operator", function() {
    return it("adds two numbers together", function() {
      return expect(1 + 2).toEqual(3);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=model_spec.map
*/
